import {
  Pensyarah,
  Pascasiswazah,
  Penyelidikan,
  HartaIntelek,
  Penyeliaan,
} from "./types";

// ============================================================
// Mock Data - Replace with actual database queries
// ============================================================

export const pensyarahData: Pensyarah[] = [
  {
    User_Name: "Dr. Ahmad bin Mohd Razali",
    User_Ic: "780512015432",
    User_NoPer: "P001",
    User_Salutation: "Dr.",
    User_Position: "Pensyarah Kanan",
    User_Dept: "Jabatan Kejuruteraan Mekanikal",
    User_KodJbtn: "JKM",
    User_Ext: "3456",
    User_Email: "ahmad.razali@university.edu.my",
    User_Status: "Aktif",
    User_NoTel: "03-87654321",
    User_SLantikan: "2010-03-15",
    User_LPertama: "2010-03-15",
    User_TmtKontrak: "2030-03-15",
    User_Gender: "Lelaki",
    User_dob: "1978-05-12",
    User_add: "No. 12, Jalan Mawar, Bangi",
    User_HP: "012-3456789",
    User_OffTel: "03-87654321",
    User_Fax: "03-87654322",
    User_GajiPokok: "8500.00",
    User_Gred: "DM54",
    User_JwtnPt: "Ketua Jabatan",
    NewUser_Dept: "Jabatan Kejuruteraan Mekanikal",
    NewUser_KodJbtn: "JKM",
    PTJ_id: "PTJ001",
    PTJ_kod: "FKAB",
    Kumpulan: "Akademik",
    Kategori: "Tetap",
    Status: "Aktif",
    Enabled: "Ya",
  },
  {
    User_Name: "Prof. Dr. Siti Aminah binti Abdullah",
    User_Ic: "750823026789",
    User_NoPer: "P002",
    User_Salutation: "Prof. Dr.",
    User_Position: "Profesor",
    User_Dept: "Jabatan Sains Komputer",
    User_KodJbtn: "JSK",
    User_Ext: "3457",
    User_Email: "siti.aminah@university.edu.my",
    User_Status: "Aktif",
    User_NoTel: "03-87654323",
    User_SLantikan: "2005-07-01",
    User_LPertama: "2005-07-01",
    User_TmtKontrak: "2035-07-01",
    User_Gender: "Perempuan",
    User_dob: "1975-08-23",
    User_add: "No. 45, Taman Ilmu, Serdang",
    User_HP: "019-8765432",
    User_OffTel: "03-87654323",
    User_Fax: "03-87654324",
    User_GajiPokok: "13500.00",
    User_Gred: "VK7",
    User_JwtnPt: "Dekan",
    NewUser_Dept: "Jabatan Sains Komputer",
    NewUser_KodJbtn: "JSK",
    PTJ_id: "PTJ002",
    PTJ_kod: "FSKTM",
    Kumpulan: "Akademik",
    Kategori: "Tetap",
    Status: "Aktif",
    Enabled: "Ya",
  },
  {
    User_Name: "Dr. Mohd Faizal bin Hassan",
    User_Ic: "820115037890",
    User_NoPer: "P003",
    User_Salutation: "Dr.",
    User_Position: "Pensyarah",
    User_Dept: "Jabatan Kejuruteraan Elektrik",
    User_KodJbtn: "JKE",
    User_Ext: "3458",
    User_Email: "faizal.hassan@university.edu.my",
    User_Status: "Aktif",
    User_NoTel: "03-87654325",
    User_SLantikan: "2015-01-10",
    User_LPertama: "2015-01-10",
    User_TmtKontrak: "2025-01-10",
    User_Gender: "Lelaki",
    User_dob: "1982-01-15",
    User_add: "No. 8, Jalan Cempaka, Kajang",
    User_HP: "017-6543210",
    User_OffTel: "03-87654325",
    User_Fax: "03-87654326",
    User_GajiPokok: "7200.00",
    User_Gred: "DM52",
    User_JwtnPt: "",
    NewUser_Dept: "Jabatan Kejuruteraan Elektrik",
    NewUser_KodJbtn: "JKE",
    PTJ_id: "PTJ003",
    PTJ_kod: "FKAB",
    Kumpulan: "Akademik",
    Kategori: "Kontrak",
    Status: "Aktif",
    Enabled: "Ya",
  },
  {
    User_Name: "Prof. Madya Dr. Nurul Huda binti Osman",
    User_Ic: "800630048901",
    User_NoPer: "P004",
    User_Salutation: "Prof. Madya Dr.",
    User_Position: "Profesor Madya",
    User_Dept: "Jabatan Biologi",
    User_KodJbtn: "JB",
    User_Ext: "3459",
    User_Email: "nurul.huda@university.edu.my",
    User_Status: "Aktif",
    User_NoTel: "03-87654327",
    User_SLantikan: "2008-09-01",
    User_LPertama: "2008-09-01",
    User_TmtKontrak: "2033-09-01",
    User_Gender: "Perempuan",
    User_dob: "1980-06-30",
    User_add: "No. 22, Taman Sains, Putrajaya",
    User_HP: "013-2345678",
    User_OffTel: "03-87654327",
    User_Fax: "03-87654328",
    User_GajiPokok: "10200.00",
    User_Gred: "DM54",
    User_JwtnPt: "Timbalan Dekan",
    NewUser_Dept: "Jabatan Biologi",
    NewUser_KodJbtn: "JB",
    PTJ_id: "PTJ004",
    PTJ_kod: "FST",
    Kumpulan: "Akademik",
    Kategori: "Tetap",
    Status: "Aktif",
    Enabled: "Ya",
  },
  {
    User_Name: "Dr. Tan Wei Ming",
    User_Ic: "850920059012",
    User_NoPer: "P005",
    User_Salutation: "Dr.",
    User_Position: "Pensyarah Kanan",
    User_Dept: "Jabatan Matematik",
    User_KodJbtn: "JM",
    User_Ext: "3460",
    User_Email: "tan.weiming@university.edu.my",
    User_Status: "Aktif",
    User_NoTel: "03-87654329",
    User_SLantikan: "2012-06-15",
    User_LPertama: "2012-06-15",
    User_TmtKontrak: "2032-06-15",
    User_Gender: "Lelaki",
    User_dob: "1985-09-20",
    User_add: "No. 5, Jalan Anggerik, Cyberjaya",
    User_HP: "016-7890123",
    User_OffTel: "03-87654329",
    User_Fax: "03-87654330",
    User_GajiPokok: "8500.00",
    User_Gred: "DM54",
    User_JwtnPt: "",
    NewUser_Dept: "Jabatan Matematik",
    NewUser_KodJbtn: "JM",
    PTJ_id: "PTJ005",
    PTJ_kod: "FST",
    Kumpulan: "Akademik",
    Kategori: "Tetap",
    Status: "Aktif",
    Enabled: "Ya",
  },
  {
    User_Name: "Dr. Rajeswari a/p Krishnan",
    User_Ic: "790415060123",
    User_NoPer: "P006",
    User_Salutation: "Dr.",
    User_Position: "Pensyarah Kanan",
    User_Dept: "Jabatan Kimia",
    User_KodJbtn: "JK",
    User_Ext: "3461",
    User_Email: "rajeswari@university.edu.my",
    User_Status: "Aktif",
    User_NoTel: "03-87654331",
    User_SLantikan: "2011-02-01",
    User_LPertama: "2011-02-01",
    User_TmtKontrak: "2031-02-01",
    User_Gender: "Perempuan",
    User_dob: "1979-04-15",
    User_add: "No. 18, Taman Harmoni, Semenyih",
    User_HP: "012-8901234",
    User_OffTel: "03-87654331",
    User_Fax: "03-87654332",
    User_GajiPokok: "8500.00",
    User_Gred: "DM54",
    User_JwtnPt: "Penyelaras Program",
    NewUser_Dept: "Jabatan Kimia",
    NewUser_KodJbtn: "JK",
    PTJ_id: "PTJ006",
    PTJ_kod: "FST",
    Kumpulan: "Akademik",
    Kategori: "Tetap",
    Status: "Aktif",
    Enabled: "Ya",
  },
  {
    User_Name: "Prof. Dr. Mohamad Zulkifli bin Yusof",
    User_Ic: "720801071234",
    User_NoPer: "P007",
    User_Salutation: "Prof. Dr.",
    User_Position: "Profesor",
    User_Dept: "Jabatan Kejuruteraan Awam",
    User_KodJbtn: "JKA",
    User_Ext: "3462",
    User_Email: "zulkifli.yusof@university.edu.my",
    User_Status: "Aktif",
    User_NoTel: "03-87654333",
    User_SLantikan: "2000-01-10",
    User_LPertama: "2000-01-10",
    User_TmtKontrak: "2030-01-10",
    User_Gender: "Lelaki",
    User_dob: "1972-08-01",
    User_add: "No. 30, Jalan Kenanga, Bangi",
    User_HP: "019-0123456",
    User_OffTel: "03-87654333",
    User_Fax: "03-87654334",
    User_GajiPokok: "14000.00",
    User_Gred: "VK7",
    User_JwtnPt: "Pengarah Pusat Penyelidikan",
    NewUser_Dept: "Jabatan Kejuruteraan Awam",
    NewUser_KodJbtn: "JKA",
    PTJ_id: "PTJ007",
    PTJ_kod: "FKAB",
    Kumpulan: "Akademik",
    Kategori: "Tetap",
    Status: "Aktif",
    Enabled: "Ya",
  },
  {
    User_Name: "Dr. Lim Chee Keong",
    User_Ic: "830305082345",
    User_NoPer: "P008",
    User_Salutation: "Dr.",
    User_Position: "Pensyarah",
    User_Dept: "Jabatan Sains Komputer",
    User_KodJbtn: "JSK",
    User_Ext: "3463",
    User_Email: "lim.ck@university.edu.my",
    User_Status: "Cuti Belajar",
    User_NoTel: "03-87654335",
    User_SLantikan: "2016-03-01",
    User_LPertama: "2016-03-01",
    User_TmtKontrak: "2026-03-01",
    User_Gender: "Lelaki",
    User_dob: "1983-03-05",
    User_add: "No. 7, Taman Teknologi, Puchong",
    User_HP: "011-2345678",
    User_OffTel: "03-87654335",
    User_Fax: "03-87654336",
    User_GajiPokok: "7200.00",
    User_Gred: "DM52",
    User_JwtnPt: "",
    NewUser_Dept: "Jabatan Sains Komputer",
    NewUser_KodJbtn: "JSK",
    PTJ_id: "PTJ002",
    PTJ_kod: "FSKTM",
    Kumpulan: "Akademik",
    Kategori: "Tetap",
    Status: "Cuti Belajar",
    Enabled: "Ya",
  },
];

export const pascasiswazahData: Pascasiswazah[] = [
  {
    StudentID: "GS001",
    StudentName: "Muhammad Hafiz bin Kamal",
    StudentIC: "920515103456",
    Programme: "PhD Kejuruteraan Mekanikal",
    Faculty: "Fakulti Kejuruteraan",
    Department: "Jabatan Kejuruteraan Mekanikal",
    SupervisorName: "Dr. Ahmad bin Mohd Razali",
    SupervisorIC: "780512015432",
    CoSupervisor: "Prof. Dr. Mohamad Zulkifli bin Yusof",
    ResearchTitle: "Kajian Bahan Komposit Baharu untuk Aplikasi Aeroangkasa",
    EnrollmentDate: "2022-09-01",
    ExpectedCompletion: "2026-08-31",
    Status: "Aktif",
    FundingSource: "FRGS",
    GrantRef: "FRGS/1/2022/TK0/UPM/02/1",
    OutputType: "Tesis",
    PublicationCount: 3,
  },
  {
    StudentID: "GS002",
    StudentName: "Nur Aisyah binti Ismail",
    StudentIC: "940320114567",
    Programme: "Master Sains Komputer",
    Faculty: "Fakulti Sains Komputer",
    Department: "Jabatan Sains Komputer",
    SupervisorName: "Prof. Dr. Siti Aminah binti Abdullah",
    SupervisorIC: "750823026789",
    CoSupervisor: "",
    ResearchTitle: "Sistem Pengesanan Penipuan Kewangan Berasaskan AI",
    EnrollmentDate: "2023-03-01",
    ExpectedCompletion: "2025-02-28",
    Status: "Aktif",
    FundingSource: "MyBrain15",
    GrantRef: "MyBrain15/2023/045",
    OutputType: "Disertasi",
    PublicationCount: 2,
  },
  {
    StudentID: "GS003",
    StudentName: "Suresh a/l Raman",
    StudentIC: "910712125678",
    Programme: "PhD Biologi",
    Faculty: "Fakulti Sains",
    Department: "Jabatan Biologi",
    SupervisorName: "Prof. Madya Dr. Nurul Huda binti Osman",
    SupervisorIC: "800630048901",
    CoSupervisor: "Dr. Rajeswari a/p Krishnan",
    ResearchTitle: "Biodiversiti Kulat Endofit di Hutan Hujan Tropika Malaysia",
    EnrollmentDate: "2021-09-01",
    ExpectedCompletion: "2025-08-31",
    Status: "Penulisan Tesis",
    FundingSource: "GRA",
    GrantRef: "GRA/FST/2021/089",
    OutputType: "Tesis",
    PublicationCount: 5,
  },
  {
    StudentID: "GS004",
    StudentName: "Chong Mei Ling",
    StudentIC: "950830136789",
    Programme: "Master Matematik",
    Faculty: "Fakulti Sains",
    Department: "Jabatan Matematik",
    SupervisorName: "Dr. Tan Wei Ming",
    SupervisorIC: "850920059012",
    CoSupervisor: "",
    ResearchTitle: "Model Matematik untuk Ramalan Penyebaran Wabak",
    EnrollmentDate: "2023-09-01",
    ExpectedCompletion: "2025-08-31",
    Status: "Aktif",
    FundingSource: "Biasiswa Universiti",
    GrantRef: "BU/FST/2023/112",
    OutputType: "Disertasi",
    PublicationCount: 1,
  },
  {
    StudentID: "GS005",
    StudentName: "Ahmad Danial bin Zainal",
    StudentIC: "930225147890",
    Programme: "PhD Kejuruteraan Elektrik",
    Faculty: "Fakulti Kejuruteraan",
    Department: "Jabatan Kejuruteraan Elektrik",
    SupervisorName: "Dr. Mohd Faizal bin Hassan",
    SupervisorIC: "820115037890",
    CoSupervisor: "Dr. Ahmad bin Mohd Razali",
    ResearchTitle: "Sistem Tenaga Boleh Diperbaharui Pintar untuk Bangunan Hijau",
    EnrollmentDate: "2022-03-01",
    ExpectedCompletion: "2026-02-28",
    Status: "Aktif",
    FundingSource: "FRGS",
    GrantRef: "FRGS/1/2022/TK0/UPM/03/5",
    OutputType: "Tesis",
    PublicationCount: 4,
  },
  {
    StudentID: "GS006",
    StudentName: "Fatimah binti Mohd Ali",
    StudentIC: "960710158901",
    Programme: "Master Kejuruteraan Awam",
    Faculty: "Fakulti Kejuruteraan",
    Department: "Jabatan Kejuruteraan Awam",
    SupervisorName: "Prof. Dr. Mohamad Zulkifli bin Yusof",
    SupervisorIC: "720801071234",
    CoSupervisor: "",
    ResearchTitle: "Analisis Kekuatan Struktur Konkrit Menggunakan Bahan Kitar Semula",
    EnrollmentDate: "2024-03-01",
    ExpectedCompletion: "2026-02-28",
    Status: "Aktif",
    FundingSource: "Biasiswa Universiti",
    GrantRef: "BU/FKAB/2024/015",
    OutputType: "Disertasi",
    PublicationCount: 0,
  },
];

export const penyelidikanData: Penyelidikan[] = [
  {
    DbName: "Pangkalan Data Bahan Komposit",
    DbDesc: "Repositori data ujian dan sifat bahan komposit untuk aplikasi aeroangkasa",
    Keyword: "komposit, aeroangkasa, bahan, ujian mekanikal",
    URL: "https://research.university.edu.my/composite-db",
    ContactIC: "780512015432",
    ContactName: "Dr. Ahmad bin Mohd Razali",
    ContactPTJ: "FKAB",
    CreatedBy: "Admin",
    CreateDate: "2022-01-15",
    SubmitDate: "2022-01-20",
    LastUpdate: "2024-11-15",
    ApproveBy: "Prof. Dr. Mohamad Zulkifli bin Yusof",
    Remarks: "Pangkalan data aktif dengan lebih 500 rekod",
    ApproveDate: "2022-02-01",
    Active: "Ya",
    Status: "Diluluskan",
  },
  {
    DbName: "AI Fraud Detection Dataset",
    DbDesc: "Dataset transaksi kewangan untuk latihan model pengesanan penipuan",
    Keyword: "AI, machine learning, penipuan, kewangan, dataset",
    URL: "https://research.university.edu.my/ai-fraud",
    ContactIC: "750823026789",
    ContactName: "Prof. Dr. Siti Aminah binti Abdullah",
    ContactPTJ: "FSKTM",
    CreatedBy: "Admin",
    CreateDate: "2023-03-10",
    SubmitDate: "2023-03-15",
    LastUpdate: "2024-10-20",
    ApproveBy: "Dekan FSKTM",
    Remarks: "Mengandungi 100,000 rekod transaksi",
    ApproveDate: "2023-04-01",
    Active: "Ya",
    Status: "Diluluskan",
  },
  {
    DbName: "Pangkalan Data Biodiversiti Kulat",
    DbDesc: "Koleksi data spesies kulat endofit dari hutan tropika Malaysia",
    Keyword: "biodiversiti, kulat, endofit, hutan tropika",
    URL: "https://research.university.edu.my/fungi-db",
    ContactIC: "800630048901",
    ContactName: "Prof. Madya Dr. Nurul Huda binti Osman",
    ContactPTJ: "FST",
    CreatedBy: "Admin",
    CreateDate: "2021-09-20",
    SubmitDate: "2021-09-25",
    LastUpdate: "2024-12-01",
    ApproveBy: "Dekan FST",
    Remarks: "Pangkalan data komprehensif dengan sampel dari 15 lokasi",
    ApproveDate: "2021-10-10",
    Active: "Ya",
    Status: "Diluluskan",
  },
  {
    DbName: "Data Tenaga Boleh Diperbaharui",
    DbDesc: "Data pemantauan panel solar dan turbin angin di kampus",
    Keyword: "tenaga solar, tenaga angin, IoT, pemantauan",
    URL: "https://research.university.edu.my/renewable-energy",
    ContactIC: "820115037890",
    ContactName: "Dr. Mohd Faizal bin Hassan",
    ContactPTJ: "FKAB",
    CreatedBy: "Admin",
    CreateDate: "2022-06-01",
    SubmitDate: "2022-06-05",
    LastUpdate: "2025-01-10",
    ApproveBy: "Prof. Dr. Mohamad Zulkifli bin Yusof",
    Remarks: "Data real-time dari 50 sensor IoT",
    ApproveDate: "2022-06-20",
    Active: "Ya",
    Status: "Diluluskan",
  },
  {
    DbName: "Model Epidemiologi",
    DbDesc: "Data dan model matematik untuk ramalan penyebaran wabak",
    Keyword: "epidemiologi, matematik, model, ramalan, wabak",
    URL: "https://research.university.edu.my/epidemic-model",
    ContactIC: "850920059012",
    ContactName: "Dr. Tan Wei Ming",
    ContactPTJ: "FST",
    CreatedBy: "Admin",
    CreateDate: "2020-04-15",
    SubmitDate: "2020-04-20",
    LastUpdate: "2024-08-30",
    ApproveBy: "Dekan FST",
    Remarks: "Digunakan untuk kajian COVID-19 dan Denggi",
    ApproveDate: "2020-05-01",
    Active: "Ya",
    Status: "Diluluskan",
  },
  {
    DbName: "Katalog Tindak Balas Kimia Hijau",
    DbDesc: "Pangkalan data tindak balas kimia mesra alam untuk industri",
    Keyword: "kimia hijau, pemangkin, tindak balas, kelestarian",
    URL: "https://research.university.edu.my/green-chem",
    ContactIC: "790415060123",
    ContactName: "Dr. Rajeswari a/p Krishnan",
    ContactPTJ: "FST",
    CreatedBy: "Admin",
    CreateDate: "2021-01-10",
    SubmitDate: "2021-01-15",
    LastUpdate: "2024-09-15",
    ApproveBy: "Dekan FST",
    Remarks: "Mengandungi 200 tindak balas kimia baharu",
    ApproveDate: "2021-02-01",
    Active: "Ya",
    Status: "Diluluskan",
  },
];

export const hartaIntelekData: HartaIntelek[] = [
  {
    IDIntellectual: 1,
    ProjectID: "PRJ001",
    ProgressID: "PROG001",
    IntellectualProperty: "Paten",
    CommercialPotential: "Tinggi",
    ProductName: "Komposit Nano-Karbon untuk Panel Pesawat",
    Country: "Malaysia",
    IntellectualStatusID: "Diluluskan",
    DateFile: "2023-01-15",
    DatePass: "2023-12-20",
    PatentNumber: "MY-2023-001234",
    Income: 150000,
    CertificateDate: "2024-01-15",
    ValidDate: "2043-01-15",
    Agent: "MTDC",
    ReferenceNo: "REF-IP-001",
    UpdatedBy: "Dr. Ahmad bin Mohd Razali",
    UpdateDate: "2024-02-01",
  },
  {
    IDIntellectual: 2,
    ProjectID: "PRJ002",
    ProgressID: "PROG002",
    IntellectualProperty: "Hak Cipta",
    CommercialPotential: "Sederhana",
    ProductName: "FraudGuard AI - Sistem Pengesanan Penipuan",
    Country: "Malaysia",
    IntellectualStatusID: "Diluluskan",
    DateFile: "2023-06-10",
    DatePass: "2024-01-15",
    PatentNumber: "HC-2024-005678",
    Income: 75000,
    CertificateDate: "2024-02-01",
    ValidDate: "2074-02-01",
    Agent: "MyIPO",
    ReferenceNo: "REF-IP-002",
    UpdatedBy: "Prof. Dr. Siti Aminah binti Abdullah",
    UpdateDate: "2024-03-15",
  },
  {
    IDIntellectual: 3,
    ProjectID: "PRJ003",
    ProgressID: "PROG003",
    IntellectualProperty: "Paten",
    CommercialPotential: "Tinggi",
    ProductName: "Bio-Fungicide dari Kulat Endofit Tempatan",
    Country: "Malaysia",
    IntellectualStatusID: "Dalam Proses",
    DateFile: "2024-03-01",
    DatePass: "",
    PatentNumber: "",
    Income: 0,
    CertificateDate: "",
    ValidDate: "",
    Agent: "MTDC",
    ReferenceNo: "REF-IP-003",
    UpdatedBy: "Prof. Madya Dr. Nurul Huda binti Osman",
    UpdateDate: "2024-10-01",
  },
  {
    IDIntellectual: 4,
    ProjectID: "PRJ004",
    ProgressID: "PROG004",
    IntellectualProperty: "Paten Utiliti",
    CommercialPotential: "Sederhana",
    ProductName: "SmartGrid Controller untuk Bangunan Hijau",
    Country: "Malaysia",
    IntellectualStatusID: "Diluluskan",
    DateFile: "2022-09-15",
    DatePass: "2023-06-01",
    PatentNumber: "PU-2023-003456",
    Income: 50000,
    CertificateDate: "2023-07-01",
    ValidDate: "2033-07-01",
    Agent: "MTDC",
    ReferenceNo: "REF-IP-004",
    UpdatedBy: "Dr. Mohd Faizal bin Hassan",
    UpdateDate: "2023-08-15",
  },
  {
    IDIntellectual: 5,
    ProjectID: "PRJ005",
    ProgressID: "PROG005",
    IntellectualProperty: "Cap Dagangan",
    CommercialPotential: "Tinggi",
    ProductName: "GreenChem Pro - Kit Eksperimen Kimia Hijau",
    Country: "Malaysia",
    IntellectualStatusID: "Diluluskan",
    DateFile: "2023-11-01",
    DatePass: "2024-05-15",
    PatentNumber: "CD-2024-007890",
    Income: 35000,
    CertificateDate: "2024-06-01",
    ValidDate: "2034-06-01",
    Agent: "MyIPO",
    ReferenceNo: "REF-IP-005",
    UpdatedBy: "Dr. Rajeswari a/p Krishnan",
    UpdateDate: "2024-07-01",
  },
];

export const penyeliaanData: Penyeliaan[] = [
  {
    SupervisionID: 1,
    SupervisorIC: "780512015432",
    SupervisorName: "Dr. Ahmad bin Mohd Razali",
    StudentIC: "920515103456",
    StudentName: "Muhammad Hafiz bin Kamal",
    Programme: "PhD Kejuruteraan Mekanikal",
    ResearchTitle: "Kajian Bahan Komposit Baharu untuk Aplikasi Aeroangkasa",
    Role: "Penyelia Utama",
    StartDate: "2022-09-01",
    EndDate: "2026-08-31",
    Status: "Aktif",
    Faculty: "Fakulti Kejuruteraan",
    Department: "Jabatan Kejuruteraan Mekanikal",
    VivaDate: "",
    Result: "",
  },
  {
    SupervisionID: 2,
    SupervisorIC: "750823026789",
    SupervisorName: "Prof. Dr. Siti Aminah binti Abdullah",
    StudentIC: "940320114567",
    StudentName: "Nur Aisyah binti Ismail",
    Programme: "Master Sains Komputer",
    ResearchTitle: "Sistem Pengesanan Penipuan Kewangan Berasaskan AI",
    Role: "Penyelia Utama",
    StartDate: "2023-03-01",
    EndDate: "2025-02-28",
    Status: "Aktif",
    Faculty: "Fakulti Sains Komputer",
    Department: "Jabatan Sains Komputer",
    VivaDate: "",
    Result: "",
  },
  {
    SupervisionID: 3,
    SupervisorIC: "800630048901",
    SupervisorName: "Prof. Madya Dr. Nurul Huda binti Osman",
    StudentIC: "910712125678",
    StudentName: "Suresh a/l Raman",
    Programme: "PhD Biologi",
    ResearchTitle: "Biodiversiti Kulat Endofit di Hutan Hujan Tropika Malaysia",
    Role: "Penyelia Utama",
    StartDate: "2021-09-01",
    EndDate: "2025-08-31",
    Status: "Penulisan Tesis",
    Faculty: "Fakulti Sains",
    Department: "Jabatan Biologi",
    VivaDate: "",
    Result: "",
  },
  {
    SupervisionID: 4,
    SupervisorIC: "850920059012",
    SupervisorName: "Dr. Tan Wei Ming",
    StudentIC: "950830136789",
    StudentName: "Chong Mei Ling",
    Programme: "Master Matematik",
    ResearchTitle: "Model Matematik untuk Ramalan Penyebaran Wabak",
    Role: "Penyelia Utama",
    StartDate: "2023-09-01",
    EndDate: "2025-08-31",
    Status: "Aktif",
    Faculty: "Fakulti Sains",
    Department: "Jabatan Matematik",
    VivaDate: "",
    Result: "",
  },
  {
    SupervisionID: 5,
    SupervisorIC: "820115037890",
    SupervisorName: "Dr. Mohd Faizal bin Hassan",
    StudentIC: "930225147890",
    StudentName: "Ahmad Danial bin Zainal",
    Programme: "PhD Kejuruteraan Elektrik",
    ResearchTitle: "Sistem Tenaga Boleh Diperbaharui Pintar untuk Bangunan Hijau",
    Role: "Penyelia Utama",
    StartDate: "2022-03-01",
    EndDate: "2026-02-28",
    Status: "Aktif",
    Faculty: "Fakulti Kejuruteraan",
    Department: "Jabatan Kejuruteraan Elektrik",
    VivaDate: "",
    Result: "",
  },
  {
    SupervisionID: 6,
    SupervisorIC: "780512015432",
    SupervisorName: "Dr. Ahmad bin Mohd Razali",
    StudentIC: "930225147890",
    StudentName: "Ahmad Danial bin Zainal",
    Programme: "PhD Kejuruteraan Elektrik",
    ResearchTitle: "Sistem Tenaga Boleh Diperbaharui Pintar untuk Bangunan Hijau",
    Role: "Penyelia Bersama",
    StartDate: "2022-03-01",
    EndDate: "2026-02-28",
    Status: "Aktif",
    Faculty: "Fakulti Kejuruteraan",
    Department: "Jabatan Kejuruteraan Elektrik",
    VivaDate: "",
    Result: "",
  },
  {
    SupervisionID: 7,
    SupervisorIC: "720801071234",
    SupervisorName: "Prof. Dr. Mohamad Zulkifli bin Yusof",
    StudentIC: "960710158901",
    StudentName: "Fatimah binti Mohd Ali",
    Programme: "Master Kejuruteraan Awam",
    ResearchTitle: "Analisis Kekuatan Struktur Konkrit Menggunakan Bahan Kitar Semula",
    Role: "Penyelia Utama",
    StartDate: "2024-03-01",
    EndDate: "2026-02-28",
    Status: "Aktif",
    Faculty: "Fakulti Kejuruteraan",
    Department: "Jabatan Kejuruteraan Awam",
    VivaDate: "",
    Result: "",
  },
  {
    SupervisionID: 8,
    SupervisorIC: "790415060123",
    SupervisorName: "Dr. Rajeswari a/p Krishnan",
    StudentIC: "910712125678",
    StudentName: "Suresh a/l Raman",
    Programme: "PhD Biologi",
    ResearchTitle: "Biodiversiti Kulat Endofit di Hutan Hujan Tropika Malaysia",
    Role: "Penyelia Bersama",
    StartDate: "2021-09-01",
    EndDate: "2025-08-31",
    Status: "Penulisan Tesis",
    Faculty: "Fakulti Sains",
    Department: "Jabatan Biologi",
    VivaDate: "",
    Result: "",
  },
  {
    SupervisionID: 9,
    SupervisorIC: "720801071234",
    SupervisorName: "Prof. Dr. Mohamad Zulkifli bin Yusof",
    StudentIC: "920515103456",
    StudentName: "Muhammad Hafiz bin Kamal",
    Programme: "PhD Kejuruteraan Mekanikal",
    ResearchTitle: "Kajian Bahan Komposit Baharu untuk Aplikasi Aeroangkasa",
    Role: "Penyelia Bersama",
    StartDate: "2022-09-01",
    EndDate: "2026-08-31",
    Status: "Aktif",
    Faculty: "Fakulti Kejuruteraan",
    Department: "Jabatan Kejuruteraan Mekanikal",
    VivaDate: "",
    Result: "",
  },
];
