using DashboardSMPPI.Models;
using System.Reflection;

namespace DashboardSMPPI.Services;

public class MockDataService
{
    public List<Pensyarah> Pensyarah { get; }
    public List<Pascasiswazah> Pascasiswazah { get; }
    public List<Penyelidikan> Penyelidikan { get; }
    public List<HartaIntelek> HartaIntelek { get; }
    public List<Penyeliaan> Penyeliaan { get; }

    public MockDataService()
    {
        Pensyarah = GeneratePensyarah();
        Pascasiswazah = GeneratePascasiswazah();
        Penyelidikan = GeneratePenyelidikan();
        HartaIntelek = GenerateHartaIntelek();
        Penyeliaan = GeneratePenyeliaan();
    }

    public List<Dictionary<string, string>> GetData(string sourceId)
    {
        return sourceId switch
        {
            "pensyarah" => ToDict(Pensyarah),
            "pascasiswazah" => ToDict(Pascasiswazah),
            "penyelidikan" => ToDict(Penyelidikan),
            "harta-intelek" => ToDict(HartaIntelek),
            "penyeliaan" => ToDict(Penyeliaan),
            _ => new()
        };
    }

    private static List<Dictionary<string, string>> ToDict<T>(List<T> items)
    {
        var props = typeof(T).GetProperties(BindingFlags.Public | BindingFlags.Instance);
        return items.Select(item =>
        {
            var dict = new Dictionary<string, string>();
            foreach (var p in props)
                dict[p.Name] = p.GetValue(item)?.ToString() ?? "";
            return dict;
        }).ToList();
    }

    private static List<Pensyarah> GeneratePensyarah() => new()
    {
        new() { User_Name="Dr. Ahmad Razak bin Ibrahim", User_Ic="750315-01-5521", User_Jawatan="Profesor Madya", User_Gred="DM52", User_NoStaff="PS001", User_Fakulti="FSKTM", User_Jabatan="Kejuruteraan Perisian", User_PtjCode="J0100", User_Email="ahmad.razak@university.edu.my", User_PhoneNo="03-79676300", User_Gelaran="Dr.", User_Gaji="12500", User_Status="Aktif", User_JenisPerkhidmatan="Tetap", User_TarikhLantikan="2005-03-15", User_KelayakanTertinggi="PhD Computer Science", User_BidangPenyelidikan="Software Engineering", User_HIndex="15", User_JumlahPenerbitan="45", User_GeranAktif="3", User_PelajarPhD="4", User_PelajarMaster="6", User_Jantina="Lelaki" },
        new() { User_Name="Prof. Dr. Siti Aminah binti Hassan", User_Ic="680720-04-6634", User_Jawatan="Profesor", User_Gred="DM54", User_NoStaff="PS002", User_Fakulti="FSKTM", User_Jabatan="Sains Komputer", User_PtjCode="J0100", User_Email="siti.aminah@university.edu.my", User_PhoneNo="03-79676301", User_Gelaran="Prof. Dr.", User_Gaji="15800", User_Status="Aktif", User_JenisPerkhidmatan="Tetap", User_TarikhLantikan="1998-07-01", User_KelayakanTertinggi="PhD Artificial Intelligence", User_BidangPenyelidikan="Machine Learning", User_HIndex="28", User_JumlahPenerbitan="112", User_GeranAktif="5", User_PelajarPhD="8", User_PelajarMaster="3", User_Jantina="Perempuan" },
        new() { User_Name="Dr. Mohd Faizal bin Abdullah", User_Ic="820105-06-7789", User_Jawatan="Pensyarah Kanan", User_Gred="DM45", User_NoStaff="PS003", User_Fakulti="Kejuruteraan", User_Jabatan="Kejuruteraan Elektrik", User_PtjCode="J0200", User_Email="faizal.abdullah@university.edu.my", User_PhoneNo="03-79676302", User_Gelaran="Dr.", User_Gaji="9500", User_Status="Aktif", User_JenisPerkhidmatan="Tetap", User_TarikhLantikan="2012-01-10", User_KelayakanTertinggi="PhD Electrical Engineering", User_BidangPenyelidikan="IoT Systems", User_HIndex="10", User_JumlahPenerbitan="32", User_GeranAktif="2", User_PelajarPhD="2", User_PelajarMaster="5", User_Jantina="Lelaki" },
        new() { User_Name="Dr. Nur Syahirah binti Kamal", User_Ic="850412-08-9902", User_Jawatan="Pensyarah Kanan", User_Gred="DM45", User_NoStaff="PS004", User_Fakulti="Sains", User_Jabatan="Matematik", User_PtjCode="J0300", User_Email="nur.syahirah@university.edu.my", User_PhoneNo="03-79676303", User_Gelaran="Dr.", User_Gaji="9200", User_Status="Aktif", User_JenisPerkhidmatan="Tetap", User_TarikhLantikan="2014-06-01", User_KelayakanTertinggi="PhD Applied Mathematics", User_BidangPenyelidikan="Data Science", User_HIndex="8", User_JumlahPenerbitan="25", User_GeranAktif="1", User_PelajarPhD="1", User_PelajarMaster="4", User_Jantina="Perempuan" },
        new() { User_Name="Dr. Muhammad Hafiz bin Othman", User_Ic="790815-10-1123", User_Jawatan="Pensyarah", User_Gred="DM41", User_NoStaff="PS005", User_Fakulti="FSKTM", User_Jabatan="Sistem Maklumat", User_PtjCode="J0100", User_Email="hafiz.othman@university.edu.my", User_PhoneNo="03-79676304", User_Gelaran="Dr.", User_Gaji="7800", User_Status="Aktif", User_JenisPerkhidmatan="Kontrak", User_TarikhLantikan="2019-09-01", User_KelayakanTertinggi="PhD Information Systems", User_BidangPenyelidikan="Cybersecurity", User_HIndex="5", User_JumlahPenerbitan="18", User_GeranAktif="1", User_PelajarPhD="0", User_PelajarMaster="3", User_Jantina="Lelaki" },
        new() { User_Name="Prof. Dr. Lim Wei Cheng", User_Ic="700210-07-3345", User_Jawatan="Profesor", User_Gred="DM54", User_NoStaff="PS006", User_Fakulti="Kejuruteraan", User_Jabatan="Kejuruteraan Mekanikal", User_PtjCode="J0200", User_Email="lim.weicheng@university.edu.my", User_PhoneNo="03-79676305", User_Gelaran="Prof. Dr.", User_Gaji="16200", User_Status="Aktif", User_JenisPerkhidmatan="Tetap", User_TarikhLantikan="1996-01-15", User_KelayakanTertinggi="PhD Mechanical Engineering", User_BidangPenyelidikan="Robotics", User_HIndex="32", User_JumlahPenerbitan="130", User_GeranAktif="4", User_PelajarPhD="6", User_PelajarMaster="2", User_Jantina="Lelaki" },
        new() { User_Name="Dr. Norazlina binti Mohd Yusof", User_Ic="830925-02-4456", User_Jawatan="Pensyarah Kanan", User_Gred="DM45", User_NoStaff="PS007", User_Fakulti="Perniagaan", User_Jabatan="Pengurusan", User_PtjCode="J0400", User_Email="norazlina@university.edu.my", User_PhoneNo="03-79676306", User_Gelaran="Dr.", User_Gaji="9800", User_Status="Aktif", User_JenisPerkhidmatan="Tetap", User_TarikhLantikan="2010-04-01", User_KelayakanTertinggi="PhD Business Management", User_BidangPenyelidikan="Strategic Management", User_HIndex="11", User_JumlahPenerbitan="38", User_GeranAktif="2", User_PelajarPhD="3", User_PelajarMaster="7", User_Jantina="Perempuan" },
        new() { User_Name="Dr. Rajesh a/l Kumar", User_Ic="880601-14-5567", User_Jawatan="Pensyarah", User_Gred="DM41", User_NoStaff="PS008", User_Fakulti="Sains", User_Jabatan="Fizik", User_PtjCode="J0300", User_Email="rajesh.kumar@university.edu.my", User_PhoneNo="03-79676307", User_Gelaran="Dr.", User_Gaji="7500", User_Status="Aktif", User_JenisPerkhidmatan="Kontrak", User_TarikhLantikan="2020-02-15", User_KelayakanTertinggi="PhD Physics", User_BidangPenyelidikan="Quantum Computing", User_HIndex="4", User_JumlahPenerbitan="12", User_GeranAktif="1", User_PelajarPhD="0", User_PelajarMaster="2", User_Jantina="Lelaki" },
        new() { User_Name="Dr. Fatimah binti Zainal", User_Ic="810318-03-6678", User_Jawatan="Profesor Madya", User_Gred="DM52", User_NoStaff="PS009", User_Fakulti="Perubatan", User_Jabatan="Perubatan Keluarga", User_PtjCode="J0500", User_Email="fatimah.zainal@university.edu.my", User_PhoneNo="03-79676308", User_Gelaran="Dr.", User_Gaji="13000", User_Status="Aktif", User_JenisPerkhidmatan="Tetap", User_TarikhLantikan="2007-08-01", User_KelayakanTertinggi="MD, PhD Public Health", User_BidangPenyelidikan="Community Health", User_HIndex="18", User_JumlahPenerbitan="55", User_GeranAktif="3", User_PelajarPhD="5", User_PelajarMaster="4", User_Jantina="Perempuan" },
        new() { User_Name="Ts. Dr. Azman bin Samsudin", User_Ic="770520-05-7789", User_Jawatan="Pensyarah Kanan", User_Gred="DS45", User_NoStaff="PS010", User_Fakulti="FSKTM", User_Jabatan="Rangkaian Komputer", User_PtjCode="J0100", User_Email="azman.samsudin@university.edu.my", User_PhoneNo="03-79676309", User_Gelaran="Ts. Dr.", User_Gaji="10200", User_Status="Aktif", User_JenisPerkhidmatan="Tetap", User_TarikhLantikan="2008-11-01", User_KelayakanTertinggi="PhD Network Security", User_BidangPenyelidikan="Network Security", User_HIndex="12", User_JumlahPenerbitan="40", User_GeranAktif="2", User_PelajarPhD="3", User_PelajarMaster="5", User_Jantina="Lelaki" },
        new() { User_Name="Dr. Tan Mei Ling", User_Ic="860715-11-8890", User_Jawatan="Pensyarah", User_Gred="DM41", User_NoStaff="PS011", User_Fakulti="Sains", User_Jabatan="Kimia", User_PtjCode="J0300", User_Email="tan.meiling@university.edu.my", User_PhoneNo="03-79676310", User_Gelaran="Dr.", User_Gaji="7600", User_Status="Tidak Aktif", User_JenisPerkhidmatan="Kontrak", User_TarikhLantikan="2018-03-15", User_KelayakanTertinggi="PhD Chemistry", User_BidangPenyelidikan="Green Chemistry", User_HIndex="6", User_JumlahPenerbitan="15", User_GeranAktif="0", User_PelajarPhD="0", User_PelajarMaster="1", User_Jantina="Perempuan" },
        new() { User_Name="Prof. Madya Dr. Zulkifli bin Harun", User_Ic="740102-09-9901", User_Jawatan="Profesor Madya", User_Gred="DM52", User_NoStaff="PS012", User_Fakulti="Kejuruteraan", User_Jabatan="Kejuruteraan Awam", User_PtjCode="J0200", User_Email="zulkifli.harun@university.edu.my", User_PhoneNo="03-79676311", User_Gelaran="Prof. Madya Dr.", User_Gaji="12800", User_Status="Aktif", User_JenisPerkhidmatan="Tetap", User_TarikhLantikan="2003-05-01", User_KelayakanTertinggi="PhD Structural Engineering", User_BidangPenyelidikan="Structural Engineering", User_HIndex="20", User_JumlahPenerbitan="65", User_GeranAktif="3", User_PelajarPhD="4", User_PelajarMaster="3", User_Jantina="Lelaki" },
    };

    private static List<Pascasiswazah> GeneratePascasiswazah() => new()
    {
        new() { StudentID="PG001", Name="Nurul Izzah binti Ahmad", Programme="PhD Computer Science", Faculty="FSKTM", Department="Kejuruteraan Perisian", Supervisor="Dr. Ahmad Razak bin Ibrahim", CoSupervisor="Prof. Dr. Siti Aminah binti Hassan", ResearchTitle="Deep Learning Approaches for Malay NLP", Status="Aktif", EnrollmentDate="2021-09-01", ExpectedCompletion="2025-08-31", FundingSource="MyBrainSc", PublicationCount="3", CGPA="3.85" },
        new() { StudentID="PG002", Name="Muhammad Amir bin Rosli", Programme="Master of Engineering", Faculty="Kejuruteraan", Department="Kejuruteraan Elektrik", Supervisor="Dr. Mohd Faizal bin Abdullah", CoSupervisor="", ResearchTitle="IoT-Based Smart Agriculture Monitoring System", Status="Aktif", EnrollmentDate="2023-02-01", ExpectedCompletion="2025-01-31", FundingSource="GRA", PublicationCount="1", CGPA="3.72" },
        new() { StudentID="PG003", Name="Priya a/p Ramasamy", Programme="PhD Artificial Intelligence", Faculty="FSKTM", Department="Sains Komputer", Supervisor="Prof. Dr. Siti Aminah binti Hassan", CoSupervisor="", ResearchTitle="Explainable AI for Medical Diagnosis", Status="Aktif", EnrollmentDate="2022-03-01", ExpectedCompletion="2026-02-28", FundingSource="FRGS", PublicationCount="5", CGPA="3.90" },
        new() { StudentID="PG004", Name="Lee Chun Wei", Programme="Master of Science", Faculty="Sains", Department="Matematik", Supervisor="Dr. Nur Syahirah binti Kamal", CoSupervisor="", ResearchTitle="Statistical Modelling of COVID-19 Transmission", Status="Tamat", EnrollmentDate="2021-09-01", ExpectedCompletion="2023-08-31", FundingSource="MyMaster", PublicationCount="2", CGPA="3.68" },
        new() { StudentID="PG005", Name="Aisha binti Mohammed", Programme="PhD Business Administration", Faculty="Perniagaan", Department="Pengurusan", Supervisor="Dr. Norazlina binti Mohd Yusof", CoSupervisor="", ResearchTitle="Digital Transformation in Malaysian SMEs", Status="Aktif", EnrollmentDate="2022-09-01", ExpectedCompletion="2026-08-31", FundingSource="Self-Funded", PublicationCount="2", CGPA="3.75" },
        new() { StudentID="PG006", Name="Vikram a/l Subramaniam", Programme="Master of Engineering", Faculty="Kejuruteraan", Department="Kejuruteraan Mekanikal", Supervisor="Prof. Dr. Lim Wei Cheng", CoSupervisor="", ResearchTitle="Autonomous Drone Navigation using SLAM", Status="Aktif", EnrollmentDate="2023-09-01", ExpectedCompletion="2025-08-31", FundingSource="GRA", PublicationCount="0", CGPA="3.60" },
        new() { StudentID="PG007", Name="Nur Dina binti Aziz", Programme="PhD Computer Science", Faculty="FSKTM", Department="Sistem Maklumat", Supervisor="Dr. Muhammad Hafiz bin Othman", CoSupervisor="Ts. Dr. Azman bin Samsudin", ResearchTitle="Blockchain-Based Identity Management", Status="Aktif", EnrollmentDate="2023-03-01", ExpectedCompletion="2027-02-28", FundingSource="FRGS", PublicationCount="1", CGPA="3.82" },
        new() { StudentID="PG008", Name="Ahmad Danial bin Ismail", Programme="PhD Physics", Faculty="Sains", Department="Fizik", Supervisor="Dr. Rajesh a/l Kumar", CoSupervisor="", ResearchTitle="Quantum Error Correction Codes", Status="Aktif", EnrollmentDate="2022-09-01", ExpectedCompletion="2026-08-31", FundingSource="MyBrainSc", PublicationCount="2", CGPA="3.88" },
        new() { StudentID="PG009", Name="Siti Khadijah binti Omar", Programme="Master of Public Health", Faculty="Perubatan", Department="Perubatan Keluarga", Supervisor="Dr. Fatimah binti Zainal", CoSupervisor="", ResearchTitle="Mental Health Screening in Rural Communities", Status="Tamat", EnrollmentDate="2022-02-01", ExpectedCompletion="2024-01-31", FundingSource="MOH Grant", PublicationCount="3", CGPA="3.91" },
        new() { StudentID="PG010", Name="Wong Jia Hao", Programme="PhD Mechanical Engineering", Faculty="Kejuruteraan", Department="Kejuruteraan Mekanikal", Supervisor="Prof. Dr. Lim Wei Cheng", CoSupervisor="Prof. Madya Dr. Zulkifli bin Harun", ResearchTitle="Soft Robotics for Rehabilitation", Status="Aktif", EnrollmentDate="2021-03-01", ExpectedCompletion="2025-02-28", FundingSource="FRGS", PublicationCount="4", CGPA="3.78" },
    };

    private static List<Penyelidikan> GeneratePenyelidikan() => new()
    {
        new() { DbName="Malaysian Academic Staff Database", DbDescription="Comprehensive database of academic staff across public universities", DbKeywords="staff, academic, university, HR", DbUrl="https://research.university.edu.my/masdb", ContactName="Dr. Ahmad Razak bin Ibrahim", ContactEmail="ahmad.razak@university.edu.my", ContactPhone="03-79676300", Faculty="FSKTM", Department="Kejuruteraan Perisian", CreationDate="2019-01-15", ApprovalDate="2019-03-01", Status="Aktif", DataSize="2.5 GB", AccessLevel="Restricted" },
        new() { DbName="Natural Language Processing Corpus", DbDescription="Malay and English parallel text corpus for NLP research", DbKeywords="NLP, corpus, Malay, language, text", DbUrl="https://research.university.edu.my/nlpcorpus", ContactName="Prof. Dr. Siti Aminah binti Hassan", ContactEmail="siti.aminah@university.edu.my", ContactPhone="03-79676301", Faculty="FSKTM", Department="Sains Komputer", CreationDate="2020-06-01", ApprovalDate="2020-08-15", Status="Aktif", DataSize="15 GB", AccessLevel="Public" },
        new() { DbName="IoT Sensor Data Repository", DbDescription="Environmental sensor readings from smart agriculture pilot", DbKeywords="IoT, sensor, agriculture, environment", DbUrl="https://research.university.edu.my/iotdata", ContactName="Dr. Mohd Faizal bin Abdullah", ContactEmail="faizal.abdullah@university.edu.my", ContactPhone="03-79676302", Faculty="Kejuruteraan", Department="Kejuruteraan Elektrik", CreationDate="2021-03-20", ApprovalDate="2021-05-01", Status="Aktif", DataSize="8 GB", AccessLevel="Restricted" },
        new() { DbName="Clinical Trial Records DB", DbDescription="Anonymized clinical trial data for public health research", DbKeywords="clinical, health, trial, medical", DbUrl="https://research.university.edu.my/clinicaldb", ContactName="Dr. Fatimah binti Zainal", ContactEmail="fatimah.zainal@university.edu.my", ContactPhone="03-79676308", Faculty="Perubatan", Department="Perubatan Keluarga", CreationDate="2018-09-01", ApprovalDate="2018-12-01", Status="Aktif", DataSize="5 GB", AccessLevel="Confidential" },
        new() { DbName="Structural Engineering Test Results", DbDescription="Material testing and structural analysis data", DbKeywords="structural, engineering, materials, testing", DbUrl="https://research.university.edu.my/structdb", ContactName="Prof. Madya Dr. Zulkifli bin Harun", ContactEmail="zulkifli.harun@university.edu.my", ContactPhone="03-79676311", Faculty="Kejuruteraan", Department="Kejuruteraan Awam", CreationDate="2017-05-15", ApprovalDate="2017-07-01", Status="Aktif", DataSize="3 GB", AccessLevel="Internal" },
        new() { DbName="SME Digital Transformation Survey", DbDescription="Survey data from Malaysian SME digital adoption study", DbKeywords="SME, digital, transformation, survey, business", DbUrl="https://research.university.edu.my/smesurvey", ContactName="Dr. Norazlina binti Mohd Yusof", ContactEmail="norazlina@university.edu.my", ContactPhone="03-79676306", Faculty="Perniagaan", Department="Pengurusan", CreationDate="2022-01-10", ApprovalDate="2022-03-15", Status="Aktif", DataSize="500 MB", AccessLevel="Public" },
        new() { DbName="Quantum Computing Simulation Data", DbDescription="Simulation results for quantum error correction research", DbKeywords="quantum, computing, simulation, physics", DbUrl="https://research.university.edu.my/quantumdb", ContactName="Dr. Rajesh a/l Kumar", ContactEmail="rajesh.kumar@university.edu.my", ContactPhone="03-79676307", Faculty="Sains", Department="Fizik", CreationDate="2023-01-01", ApprovalDate="2023-02-15", Status="Dalam Pembangunan", DataSize="1 GB", AccessLevel="Internal" },
        new() { DbName="Network Intrusion Detection Dataset", DbDescription="Network traffic data for cybersecurity ML training", DbKeywords="network, security, intrusion, cybersecurity, ML", DbUrl="https://research.university.edu.my/nidds", ContactName="Ts. Dr. Azman bin Samsudin", ContactEmail="azman.samsudin@university.edu.my", ContactPhone="03-79676309", Faculty="FSKTM", Department="Rangkaian Komputer", CreationDate="2020-11-01", ApprovalDate="2021-01-15", Status="Aktif", DataSize="12 GB", AccessLevel="Restricted" },
    };

    private static List<HartaIntelek> GenerateHartaIntelek() => new()
    {
        new() { IDIntellectual="IP001", ProjectID="PRJ-2020-001", Title="Smart IoT Irrigation Controller", Type="Paten", PatentNumber="MY-2021-004532", FilingDate="2021-03-15", ApprovalDate="2023-06-01", ExpiryDate="2041-03-15", Inventors="Dr. Mohd Faizal bin Abdullah", Faculty="Kejuruteraan", Status="Granted", CommercialPotential="Tinggi", LicenseIncome="15000", Agent="MyIPO", Country="Malaysia", Category="Engineering", Description="IoT-based smart irrigation system with soil moisture sensing" },
        new() { IDIntellectual="IP002", ProjectID="PRJ-2019-008", Title="Malay Text Summarization Algorithm", Type="Hakcipta", PatentNumber="", FilingDate="2020-01-10", ApprovalDate="2020-03-01", ExpiryDate="", Inventors="Prof. Dr. Siti Aminah binti Hassan", Faculty="FSKTM", Status="Granted", CommercialPotential="Sederhana", LicenseIncome="5000", Agent="", Country="Malaysia", Category="Software", Description="Novel algorithm for automatic Malay text summarization" },
        new() { IDIntellectual="IP003", ProjectID="PRJ-2021-015", Title="Biodegradable Polymer Composite", Type="Paten", PatentNumber="MY-2022-007891", FilingDate="2022-05-20", ApprovalDate="", ExpiryDate="", Inventors="Dr. Tan Mei Ling", Faculty="Sains", Status="Dalam Proses", CommercialPotential="Tinggi", LicenseIncome="0", Agent="MyIPO", Country="Malaysia", Category="Materials Science", Description="Eco-friendly biodegradable polymer for packaging" },
        new() { IDIntellectual="IP004", ProjectID="PRJ-2022-003", Title="Robotic Rehabilitation Glove", Type="Paten", PatentNumber="US-2023-0145678", FilingDate="2023-01-08", ApprovalDate="", ExpiryDate="", Inventors="Prof. Dr. Lim Wei Cheng, Wong Jia Hao", Faculty="Kejuruteraan", Status="Dalam Proses", CommercialPotential="Tinggi", LicenseIncome="0", Agent="USPTO", Country="United States", Category="Medical Device", Description="Soft robotic glove for stroke rehabilitation" },
        new() { IDIntellectual="IP005", ProjectID="PRJ-2018-012", Title="Structural Health Monitoring System", Type="Utility Innovation", PatentNumber="MY-UI-2019-002345", FilingDate="2019-07-15", ApprovalDate="2020-09-01", ExpiryDate="2029-07-15", Inventors="Prof. Madya Dr. Zulkifli bin Harun", Faculty="Kejuruteraan", Status="Granted", CommercialPotential="Sederhana", LicenseIncome="8000", Agent="MyIPO", Country="Malaysia", Category="Engineering", Description="Wireless sensor network for bridge structural monitoring" },
        new() { IDIntellectual="IP006", ProjectID="PRJ-2023-007", Title="Blockchain Academic Credential Verification", Type="Hakcipta", PatentNumber="", FilingDate="2023-09-01", ApprovalDate="2023-10-15", ExpiryDate="", Inventors="Dr. Muhammad Hafiz bin Othman, Ts. Dr. Azman bin Samsudin", Faculty="FSKTM", Status="Granted", CommercialPotential="Tinggi", LicenseIncome="0", Agent="", Country="Malaysia", Category="Software", Description="DApp for verifying academic credentials via blockchain" },
        new() { IDIntellectual="IP007", ProjectID="PRJ-2020-020", Title="Herbal Extract Formulation", Type="Paten", PatentNumber="MY-2021-009876", FilingDate="2021-11-20", ApprovalDate="2024-01-15", ExpiryDate="2041-11-20", Inventors="Dr. Fatimah binti Zainal", Faculty="Perubatan", Status="Granted", CommercialPotential="Sederhana", LicenseIncome="12000", Agent="MyIPO", Country="Malaysia", Category="Pharmaceutical", Description="Traditional herbal extract for diabetes management" },
    };

    private static List<Penyeliaan> GeneratePenyeliaan() => new()
    {
        new() { SupervisionID="SV001", SupervisorName="Dr. Ahmad Razak bin Ibrahim", StudentName="Nurul Izzah binti Ahmad", Programme="PhD Computer Science", Faculty="FSKTM", ResearchTitle="Deep Learning Approaches for Malay NLP", Role="Penyelia Utama", StartDate="2021-09-01", EndDate="2025-08-31", Status="Aktif", VivaDate="", VivaResult="", PublicationCount="3" },
        new() { SupervisionID="SV002", SupervisorName="Prof. Dr. Siti Aminah binti Hassan", StudentName="Nurul Izzah binti Ahmad", Programme="PhD Computer Science", Faculty="FSKTM", ResearchTitle="Deep Learning Approaches for Malay NLP", Role="Penyelia Bersama", StartDate="2021-09-01", EndDate="2025-08-31", Status="Aktif", VivaDate="", VivaResult="", PublicationCount="3" },
        new() { SupervisionID="SV003", SupervisorName="Dr. Mohd Faizal bin Abdullah", StudentName="Muhammad Amir bin Rosli", Programme="Master of Engineering", Faculty="Kejuruteraan", ResearchTitle="IoT-Based Smart Agriculture Monitoring System", Role="Penyelia Utama", StartDate="2023-02-01", EndDate="2025-01-31", Status="Aktif", VivaDate="", VivaResult="", PublicationCount="1" },
        new() { SupervisionID="SV004", SupervisorName="Prof. Dr. Siti Aminah binti Hassan", StudentName="Priya a/p Ramasamy", Programme="PhD Artificial Intelligence", Faculty="FSKTM", ResearchTitle="Explainable AI for Medical Diagnosis", Role="Penyelia Utama", StartDate="2022-03-01", EndDate="2026-02-28", Status="Aktif", VivaDate="", VivaResult="", PublicationCount="5" },
        new() { SupervisionID="SV005", SupervisorName="Dr. Nur Syahirah binti Kamal", StudentName="Lee Chun Wei", Programme="Master of Science", Faculty="Sains", ResearchTitle="Statistical Modelling of COVID-19 Transmission", Role="Penyelia Utama", StartDate="2021-09-01", EndDate="2023-08-31", Status="Tamat", VivaDate="2023-07-15", VivaResult="Lulus", PublicationCount="2" },
        new() { SupervisionID="SV006", SupervisorName="Dr. Norazlina binti Mohd Yusof", StudentName="Aisha binti Mohammed", Programme="PhD Business Administration", Faculty="Perniagaan", ResearchTitle="Digital Transformation in Malaysian SMEs", Role="Penyelia Utama", StartDate="2022-09-01", EndDate="2026-08-31", Status="Aktif", VivaDate="", VivaResult="", PublicationCount="2" },
        new() { SupervisionID="SV007", SupervisorName="Prof. Dr. Lim Wei Cheng", StudentName="Vikram a/l Subramaniam", Programme="Master of Engineering", Faculty="Kejuruteraan", ResearchTitle="Autonomous Drone Navigation using SLAM", Role="Penyelia Utama", StartDate="2023-09-01", EndDate="2025-08-31", Status="Aktif", VivaDate="", VivaResult="", PublicationCount="0" },
        new() { SupervisionID="SV008", SupervisorName="Dr. Muhammad Hafiz bin Othman", StudentName="Nur Dina binti Aziz", Programme="PhD Computer Science", Faculty="FSKTM", ResearchTitle="Blockchain-Based Identity Management", Role="Penyelia Utama", StartDate="2023-03-01", EndDate="2027-02-28", Status="Aktif", VivaDate="", VivaResult="", PublicationCount="1" },
        new() { SupervisionID="SV009", SupervisorName="Ts. Dr. Azman bin Samsudin", StudentName="Nur Dina binti Aziz", Programme="PhD Computer Science", Faculty="FSKTM", ResearchTitle="Blockchain-Based Identity Management", Role="Penyelia Bersama", StartDate="2023-03-01", EndDate="2027-02-28", Status="Aktif", VivaDate="", VivaResult="", PublicationCount="1" },
        new() { SupervisionID="SV010", SupervisorName="Dr. Fatimah binti Zainal", StudentName="Siti Khadijah binti Omar", Programme="Master of Public Health", Faculty="Perubatan", ResearchTitle="Mental Health Screening in Rural Communities", Role="Penyelia Utama", StartDate="2022-02-01", EndDate="2024-01-31", Status="Tamat", VivaDate="2023-12-10", VivaResult="Lulus dengan Pembetulan", PublicationCount="3" },
        new() { SupervisionID="SV011", SupervisorName="Prof. Dr. Lim Wei Cheng", StudentName="Wong Jia Hao", Programme="PhD Mechanical Engineering", Faculty="Kejuruteraan", ResearchTitle="Soft Robotics for Rehabilitation", Role="Penyelia Utama", StartDate="2021-03-01", EndDate="2025-02-28", Status="Aktif", VivaDate="", VivaResult="", PublicationCount="4" },
        new() { SupervisionID="SV012", SupervisorName="Prof. Madya Dr. Zulkifli bin Harun", StudentName="Wong Jia Hao", Programme="PhD Mechanical Engineering", Faculty="Kejuruteraan", ResearchTitle="Soft Robotics for Rehabilitation", Role="Penyelia Bersama", StartDate="2021-03-01", EndDate="2025-02-28", Status="Aktif", VivaDate="", VivaResult="", PublicationCount="4" },
        new() { SupervisionID="SV013", SupervisorName="Dr. Rajesh a/l Kumar", StudentName="Ahmad Danial bin Ismail", Programme="PhD Physics", Faculty="Sains", ResearchTitle="Quantum Error Correction Codes", Role="Penyelia Utama", StartDate="2022-09-01", EndDate="2026-08-31", Status="Aktif", VivaDate="", VivaResult="", PublicationCount="2" },
    };
}
